---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true

ratings:
   paths:
   - "**.rb"
   - "**.md"

exclude_paths:
  - test/**/*
