AllCops:
  Exclude:
    - 'bin/**/*'
    - '**/vendor/**/*'
  Include:
    - '**/*.rb'
    - '**/Gemfile'
    - '**/*.rake'
    - '*.gemspec'
    - 'Appraisals'
    - 'Rakefile'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 115

Style/Documentation:
  Enabled: false
