language: ruby

rvm:
  - ruby-head
  - 2.3.1
  - 2.2.5

gemfile:
  - gemfiles/activerecord_5_0.gemfile
  - gemfiles/github_head.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/github_head.gemfile

before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler

bundler_args: --without tools --jobs=3 --retry=3

branches:
  only:
    - master

sudo: false

cache: bundler

notifications:
  email: false
