sudo: false

cache: bundler

language: ruby

rvm:
  - ruby-head
  - 2.3.3
  - 2.2.6

gemfile:
  - gemfiles/activerecord_5_0.gemfile
  - gemfiles/github_head.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/github_head.gemfile

bundler_args: --without tools --jobs=3 --retry=3

script:
  - bundle exec rake test
  - bundle exec rubocop

after_success:
  - bundle exec codeclimate-test-reporter

notifications:
  email: false

# MAYBE: Use ENV var or encrypted token?
# addons:
#   code_climate:
#     repo_token: <token>
